[[stopwords]]
== 停用词: 性能与精度

从早期的信息检索到如今，((("stopwords", "performance versus precision"))) 我们已习惯于磁盘空间和内存被限制为很小一部分，所以
必须使你的索引尽可能小。 kilobyte 保存能力在性能上有显著的改善。  (查看 <<stemming>> ) 拦截(stemming)很重要， 现在
我们使用相同的方式增加索引，不仅搜索范围更广， 并且也能作为压缩索引的一种方式。

一种最简单的减少索引大小的方法就是 _索引字数少_。  出于搜索
目的，某些单词比其他重要.可以通过选择更加重要的术语来显著减少索引的大小。

那么，哪些词条可以被过滤呢？((("term frequency", "high and low"))) 我们可以简单分为两组:

低频术语::

词语出现在相对较少的文档或集合中。由于它们的稀有性，((("weight", "low frequency terms"))) 他们拥有较长的值或者_较重_。

高频术语::

出现在许多文件索引中的常用词语，例如 `the`、`and`、和`is`。 上述词所低重量并有助于少的相关评分。

[TIP]
==================================================

当然，频率作为标记的刻度，不仅仅分为_低_和_高_。 我们只是以某一个点作为分界线，低于分界线的词为低频词，之上的为高频词。

==================================================

这术语低频或高频取决于文档本身。如果所有都是中文文档，那么 `and` 就是低频词汇
在数据库相关的文档中，高频词汇`database`可能很少作为特定集合的搜素词。

可以说，任何语言都会出现一些高频词汇，但是对搜索没有什么价值。((("English", "stopwords"))) 默认英文语言中，ElasticSearch 使用的停用词如下

    a, an, and, are, as, at, be, but, by, for, if, in, into, is, it,
    no, not, of, on, or, such, that, the, their, then, there, these,
    they, this, to, was, will, with

在检索时这些停用词通过会被过滤掉，同时也会产生一些负面的影响。但是这样子做肯定是一个比较好的解决方案？

[[pros-cons-stopwords]]
[float="true"]
=== 停用词的优点和缺点

现在我们拥有更大的磁盘空间，更多内存，并且((("stopwords", "pros and cons of")))还有更好的压缩算法。
索引经过排除33%的常用词条后,一万份文档仅减少4MB空间。 所以使用停用词减少索引大小不再是一个有效的理由。
(不过这种说法还有一点需要注意，我们在 <<stopwords-phrases>> 讨论。)

重要的一点是，通过删除索引的停用词，我们在搜索类型的索引时准确度就下降了。 例如以下词条过滤掉停用就没有意义了:

* 区分 _happy_ 和 _not happy_.
* 搜索乐队名称 The The.
* 查找莎士比亚的语录 ``To be, or not to be''
* 使用挪威的国家代码: `no`

去掉停用词的优点主要是性能上的提高。试想一下在100w的文档索引中搜索`fox`。也许`fox`
在其中只出现20次。意味着elasticserach只需从20个相关的文档中检索返回前10的结果. 现在, 
我们将搜索内容改为 `the OR fox`。`the` 词条几乎出现在所有的文档中,意味着 Elasticsearch 需要全文档检索, 由此可见第二种方式的性能远远不及第二种。

好在还有一些技巧，我们可以用来保持常用词搜索，同时还可以保持良好的性能。首先我们一块学习如何使用停用词。



